#!/bin/bash -e

# if no arguments are given, echo the usage string
if [ $# -lt 1 ]; then
  echo 'Usage: convert_video [path_to_input] [output_name]' >&2
  exit 1
fi

ffmpeg -i $1 -c:v copy -f mp4 $2".mp4"
