#!/bin/bash
# NAME
#	mydiff -- Uses Sublime Text diff and merge tool Sublimerge as diff tool.
#
# SYNOPSIS
#	mydiff FILE_LEFT FILE_RIGHT
#
# DESCRIPTION
#	Opens up Sublime and compares FILE_LEFT and FILE_RIGHT using Sublimerge.
#
# OPTIONS
#	-1	?description?
#
#
# ENVIRONMENT
#	The following environment variables affect the execution of name:
#	?VAR1?	?description?
#
# EXIT STATUS
#
# EXAMPLES
#	?example 1? ?description?
#		?example 1?
#
# BUGS
#	bug1
#
# Written by: Rowland O'Flaherty (rowlandoflaherty.com)
# Created on: 02/02/14/

number=$(ps aux | grep Sublime | wc -l)
if [ $number -gt 1 ]; then
    subl_ln -n --wait "$1" "$2" --command "sublimerge_diff_views {\"left_read_only\": true, \"right_read_only\": true}"
else
    open -g /Applications/Sublime\ Text.app/
    sleep 1.4
    subl_ln -n --wait "$1" "$2" --command "sublimerge_diff_views {\"left_read_only\": true, \"right_read_only\": true}"
    osascript -e "tell application \"Sublime Text\" to quit"
fi

